hashids:
  length: 12
  secret: "6ab6122836cfef95f8db"

language:
  local: zh-cn

mail:
  host: "smtp.163.com"
  pass: ""
  port: 465
  to: ""
  user: ""

mysql:
  connmaxlifetime: 60
  maxidleconn: 60
  maxopenconn: 10
  addr: "127.0.0.1:3306"
  name: "db_go_gin"
  pass: "123456789"
  user: "root"

redis:
  addr: "127.0.0.1:6379"
  db: "0"
  maxretries: 3
  minidleconns: 5
  pass: ""
  poolsize: 10
